### ISSUE TITLE
DefaultIndex not working for all Elements..

### ISSUE THREAD

**Issue by LewBr** [gigantessbeta/SendUIAPI#2]
I am using your code as well, so at first thank you very much for that awesome code!

But i have a problem, when i try to set the default index of Dropdown, Toggle, StepSlider it not works, i have tested on all of that, and even if i try to do for example: `->defaultIndex("OP全員")` it keeps on the first selected, so how can i fix that?

**Comment by MyDeacy** [comment]
In the case of toggle, you can specify the initial value with defaultValue() to specify the initial value and defaultOptionIndex() for Dropdown.

This is clearly stated in the source, it is not a code mistake.

**Comment by LewBr** [comment]
I have tryed doing that but even when i do this:
` $form->addContent((new Toggle)->text("§aTest.")->defaultValue(true));`
It keeps the toggle bar disabled like when is false.. what i am doing wrong?

**Comment by MyDeacy** [comment]
By setting it to true, toggle gets brightened (selected).
You should specify false.
If you specify false, defaultValue () is unnecessary.
